Feature/footer
W-Sei/ice-cream-with-passion pull request #2
Opened 2022-10-08 22:43 UTC by Kate-Lesnyak

2022-10-08 23:24 UTC, W-Sei commented on src/partials/footer.html
> +      <p class="page-footer__title page-footer__title_dubbed">homemade ice cream
Please, make the class name BEM, for example:
change this: page-footer__title_dubbed
to this: page-footer__title--dubbed

2022-10-08 23:25 UTC, W-Sei commented on src/partials/footer.html
> +        <br>
please, try to avoid using <br>, may be, reshape the line with CSS

2022-10-08 23:29 UTC, W-Sei commented on src/partials/footer.html
> +        <a class="social-list__link" href="https://www.github.com" aria-label="github" target="_blank" rel="noopener noreferrer">
Please, consider changing rel to "nofollow noopener noreferrer"

2022-10-08 23:40 UTC, W-Sei commented on src/sass/layout/_footer.scss
> +  .page-footer__container {
please, renew main, class .container has paddings, no need to duplicate

2022-10-08 23:44 UTC, W-Sei commented on src/sass/layout/_footer.scss
> +.page-footer__text,
page footer text 16px on desktop

2022-10-08 23:50 UTC, W-Sei requested changes
Старт чудовий, але треба трошки доробити).
Окрім коментів тут, основне - будь ласка, звірся з макетом, на десктопі, планшеті та мобілці виникає обрізаність, не зовсім вірні марджини, розмітка.

2022-10-09 07:41 UTC, Kate-Lesnyak commented on src/sass/layout/_footer.scss
> +  .page-footer__container {
Я не дублирую потому что по разметке здесь не секция с классом section как в мэйне, а отдельный подвал

2022-10-09 07:41 UTC, Kate-Lesnyak commented on src/partials/footer.html
> +        <a class="social-list__link" href="https://www.github.com" aria-label="github" target="_blank" rel="noopener noreferrer">
посмотрю

2022-10-09 07:43 UTC, Kate-Lesnyak commented on src/partials/footer.html
> +        <br>
https://ru.bem.info/methodology/naming-convention/#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B8%D0%BC%D0%B5%D0%BD 

Я делала по БЕМ. Есть основные правила через одно нижнее подчеркивание. А через -- это альтернативное решение. Двойной дефис внутри комментария (--) может вызвать ошибки при [валидации HTML-документа](http://www.w3.org/TR/html5/syntax.html#comments).

2022-10-09 07:44 UTC, Kate-Lesnyak commented on src/partials/footer.html
> +      <p class="page-footer__title page-footer__title_dubbed">homemade ice cream
https://ru.bem.info/methodology/naming-convention/#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B8%D0%BC%D0%B5%D0%BD

Я делала по БЕМ. Есть основные правила через одно нижнее подчеркивание. А через -- это альтернативное решение. Двойной дефис внутри комментария (--) может вызвать ошибки при [валидации HTML-документа](http://www.w3.org/TR/html5/syntax.html#comments).

2022-10-09 07:44 UTC, Kate-Lesnyak commented on src/partials/footer.html
> +        <br>
попробую через 2 отдельных р

2022-10-09 07:49 UTC, Kate-Lesnyak commented on src/sass/layout/_footer.scss
> +.page-footer__text,
а на мобильной 12рх, а на таблет 14рх))

2022-10-09 08:28 UTC, Kate-Lesnyak commented on src/sass/layout/_footer.scss
> +.page-footer__text,
я делаю с мобайл, адапитацию еще не делала

2022-10-09 08:32 UTC, Kate-Lesnyak commented on src/partials/footer.html
> +        <br>
попробую

2022-10-09 08:33 UTC, Kate-Lesnyak commented on src/partials/footer.html
> +      <p class="page-footer__title page-footer__title_dubbed">homemade ice cream
Командой как решили делать по БЕМ?

2022-10-09 16:58 UTC, W-Sei commented on src/partials/footer.html
> +      <p class="page-footer__title page-footer__title_dubbed">homemade ice cream
Ось так: (--)

2022-10-09 16:59 UTC, W-Sei commented on src/partials/footer.html
> +        <br>
Дякую! :)

2022-10-09 16:59 UTC, W-Sei commented on src/partials/footer.html
> +        <a class="social-list__link" href="https://www.github.com" aria-label="github" target="_blank" rel="noopener noreferrer">
+ :)

2022-10-09 16:59 UTC, W-Sei commented on src/sass/layout/_footer.scss
> +  .page-footer__container {
+

2022-10-09 17:00 UTC, W-Sei commented on src/sass/layout/_footer.scss
> +.page-footer__text,
Зрозуміла, сорі :)

2022-10-11 13:55 UTC, W-Sei approved these changes

2022-10-11 13:56 UTC, merged